### ISSUE TITLE
Use an "opt-in" model for the script

### ISSUE THREAD

**Issue by alexolog** [machsix/Super-preloader#428]
I only use the script for autopaging (not preloading) but it would automatically use the preloading functionality if a URLmatches one of the built-in rules.

The problem is that the preloading can break the functionality of important sites, such as financial institutions, government services, etc.  I have encountered issues with online banking, tax preparation and submitting, etc.

An old Autopager eddon that I used to use before the WebExtensions switch would pop up a dialog when navigating to new sites saying that a rule was found that matches the site and ask me if I wanted to enable autopaging on that site (it was also possible to change the decision later)

It would be great if this script could likewise have an "opt in" mode in which sites will not be processed at all unless explicitly told to use either preloading or autopaging (as appropriate)

**Comment by machsix** [comment]
<img width="351" alt="Capture" src="https://user-images.githubusercontent.com/28209092/98631936-4b32db00-22d3-11eb-8c55-8255f2b240eb.PNG">

Configure it as the above should work. I can also add an option to disable rules in this file https://github.com/machsix/Super-preloader/blob/master/src/rules/jsGeneralRule.js . But I'm too lazy to do it now.

<img width="301" alt="Capture" src="https://user-images.githubusercontent.com/28209092/98632108-aa90eb00-22d3-11eb-9afd-574e42fb50f9.PNG">

In addition, you can always disable a rule for a website. 


I don't like the idea of a popup dialog to confirm whether you want to enable the rule for a website (whitelist mode). First, popup dialog itself is annoying. Second, it's hard to handle the storage of user configurations for whitelists. If you store that with GM_setValue api, it can be unpredictable when you reinstall the script (trust me, I have been though this when I refactored the script. https://greasyfork.org/en/scripts/33522-super-preloaderplus-one-new/discussions/33898 Many people completely failed to use the script due to script manager's handling). If you store in localStorage, someone who are very serious about privacy and clean cookie/localstorage frequently can run into trouble.

**Comment by LurkerHub** [comment]
Is the "enable" checkbox per domain?

**Comment by machsix** [comment]
It's per origin. Check https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage for detail

**Comment by LurkerHub** [comment]
Thanks.

**Comment by LurkerHub** [comment]
> I don't like the idea of a popup dialog to confirm whether you want to enable the rule for a website (whitelist mode). First, popup dialog itself is annoying. Second, it's hard to handle the storage of user configurations for whitelists. If you store that with GM_setValue api, it can be unpredictable when you reinstall the script (trust me, I have been though this when I refactored the script. https://greasyfork.org/en/scripts/33522-super-preloaderplus-one-new/discussions/33898 Many people completely failed to use the script due to script manager's handling). If you store in localStorage, someone who are very serious about privacy and clean cookie/localstorage frequently can run into trouble.

Where do you store the enabled/disabled status of different origins then?

**Comment by machsix** [comment]
If you made any modifications through the float window and save it, a variable named `spfwset` is saved in the localStorage

You can use `JSON.parse(localStorage.getItem('spfwset'))` to view it. Key `enable` determines whether the rule is enabled or not. `a_enable` determines whether `Autopager` mode is enabled

**Comment by LurkerHub** [comment]
Evaluating `JSON.parse(localStorage.getItem('spfwset'))` in the console returns `null`
I definitely disabled the script on some sites.  What am I missing?

**Comment by LurkerHub** [comment]
> <img alt="Capture" width="351" src="https://user-images.githubusercontent.com/28209092/98631936-4b32db00-22d3-11eb-8c55-8255f2b240eb.PNG">
> 
> Configure it as the above should work.

When I configure it as the above and go to, for example, https://www.simplemachines.org/community/index.php?board=1.0, I see no way to enable it for that origin since the floating window disappears.

**Comment by heroboy** [comment]
> I can also add an option to disable rules in this file https://github.com/machsix/Super-preloader/blob/master/src/rules/jsGeneralRule.js . But I'm too lazy to do it now.

The "disable builtin rules" may do this. It disables both `siterules` and `generalrules`.

And "disable rule subscription" disabled the rules that are from a downloaded json file.

**Comment by LurkerHub** [comment]
The problem with the disable options is that they seem to prevent the floating window from appearing, which does not allow an easy "opt in" for a site.

This is an important part -- we need to be able to enable a rule on a site in the "default off" mode as easily as we can disable it in the current "default on" mode.

**Comment by machsix** [comment]
Close the issue since I have no interest for whitelist mode in the script at all. 

If you need the function, you can edit the website where the script is enabled in the meta data part of the script.
